[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npm run build:production"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 